package com.vliveconvert.app.ui.theme

import androidx.compose.ui.graphics.Color

// vivo 品牌蓝 #415FFF 派生的 M3 色调

// 浅色方案
val LightPrimary = Color(0xFF415FFF)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFDEE0FF)
val LightOnPrimaryContainer = Color(0xFF001158)
val LightSecondary = Color(0xFF5A5D72)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFDFE1F9)
val LightOnSecondaryContainer = Color(0xFF171A2C)
val LightTertiary = Color(0xFF76547E)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFDD7FC)
val LightOnTertiaryContainer = Color(0xFF2D1235)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFBF8FF)
val LightOnBackground = Color(0xFF1B1B21)
val LightSurface = Color(0xFFFBF8FF)
val LightOnSurface = Color(0xFF1B1B21)
val LightSurfaceVariant = Color(0xFFE3E1EC)
val LightOnSurfaceVariant = Color(0xFF46464F)
val LightOutline = Color(0xFF767680)
val LightOutlineVariant = Color(0xFFC7C5D0)
val LightSurfaceContainerLow = Color(0xFFF5F2FA)
val LightSurfaceContainer = Color(0xFFEFEDF6)
val LightSurfaceContainerHigh = Color(0xFFE9E7F0)
val LightInverseSurface = Color(0xFF303036)
val LightInverseOnSurface = Color(0xFFF2EFF7)
val LightInversePrimary = Color(0xFFBAC3FF)

// 深色方案
val DarkPrimary = Color(0xFFBAC3FF)
val DarkOnPrimary = Color(0xFF082491)
val DarkPrimaryContainer = Color(0xFF2A41B8)
val DarkOnPrimaryContainer = Color(0xFFDEE0FF)
val DarkSecondary = Color(0xFFC3C5DD)
val DarkOnSecondary = Color(0xFF2C2F42)
val DarkSecondaryContainer = Color(0xFF434559)
val DarkOnSecondaryContainer = Color(0xFFDFE1F9)
val DarkTertiary = Color(0xFFE9BBE0)
val DarkOnTertiary = Color(0xFF45264D)
val DarkTertiaryContainer = Color(0xFF5D3C65)
val DarkOnTertiaryContainer = Color(0xFFFDD7FC)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF121318)
val DarkOnBackground = Color(0xFFE4E1E9)
val DarkSurface = Color(0xFF121318)
val DarkOnSurface = Color(0xFFE4E1E9)
val DarkSurfaceVariant = Color(0xFF46464F)
val DarkOnSurfaceVariant = Color(0xFFC7C5D0)
val DarkOutline = Color(0xFF91909A)
val DarkOutlineVariant = Color(0xFF46464F)
val DarkSurfaceContainerLow = Color(0xFF1A1B20)
val DarkSurfaceContainer = Color(0xFF1E1F25)
val DarkSurfaceContainerHigh = Color(0xFF282A2F)
val DarkInverseSurface = Color(0xFFE4E1E9)
val DarkInverseOnSurface = Color(0xFF2F3036)
val DarkInversePrimary = Color(0xFF415FFF)
